name: 'PROD deploy version'
run-name: 'PROD deploy version ${{ inputs.environment }} to ${{ inputs.postID }} by @${{ github.actor }}'

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: 'Tag version to deploy'
        required: true
        default: 'v1.0.0'
      environment:
        description: 'Deployment environment'
        required: true
        default: 'default'
        type: choice
        options:
          - FALLBACK
          - PROD

jobs:
  version-switch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Switch to specific tag
        run: |
          git fetch --tags
          git checkout ${{ github.event.inputs.version }}

  upload_prod_wordpress_to_prod_s3:
    needs: version-switch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set environment variables
        run: |
          if [ "${{ github.event.inputs.environment }}" == "fallback" ]; then
            echo "AWS_BUCKET=${{ secrets.PROD_AWS_BUCKET }}" >> $GITHUB_ENV
            echo "CLOUDFRONT_DIST_ID=${{ secrets.PROD_CLOUDFRONT_DIST_ID }}" >> $GITHUB_ENV
          else
            echo "AWS_BUCKET=${{ secrets.FALLBACK_AWS_BUCKET }}" >> $GITHUB_ENV
            echo "CLOUDFRONT_DIST_ID=${{ secrets.FALLBACK_CLOUDFRONT_DIST_ID }}" >> $GITHUB_ENV
          fi

      - name: Upload HTML to S3
        uses: reggionick/s3-deploy@v4
        with:
          folder: dist
          bucket: ${{ env.AWS_BUCKET }}
          bucket-region: ${{ secrets.AWS_REGION }}
          dist-id: ${{ env.CLOUDFRONT_DIST_ID }}
          invalidation: /
          delete-removed: true
          no-cache: true
          private: true
          files-to-include: '{.*/**,**}'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}