name: "Upload to S3 Job"
description: "Uploads HTML files to AWS S3 bucket"

on:
  workflow_call:
    jobs:
      upload_to_s3:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repository
            uses: actions/checkout@v3
          - name: Upload HTML to S3
            uses: jakejarvis/s3-sync-action@master
            with:
              args: --acl public-read --follow-symlinks --delete
            env:
              AWS_S3_BUCKET: orcid-qa-public-page
              AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
              AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              AWS_REGION: 'us-east-1'
              SOURCE_DIR: 'dist'