name: Clone WordPress Post

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: string
        description: "The deployment environment (QA, SBOX, PROD)"
      postID:
        required: true
        type: string
        description: "The ID of the post to clone"

jobs:
  clone_post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run cloning script
        run: python wordpress-cloning-script.py ${{ inputs.environment }} ${{ inputs.postID }}

      - name: Configure git user
        run: |
          git config user.name 'GitHub Actions'
          git config user.email 'actions@github.com'

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Cloned WordPress post ${{ inputs.postID }} for environment ${{ inputs.environment }}" --allow-empty
          git push