name: Clone Wordpress QA

on:
  workflow_dispatch:
    inputs:
      postID:
        required: true
        type: string
        description: "The ID of the post to clone"
        default: "24531"
jobs:
  clone_post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Clone Post
        uses: clone-post.yml
        with:
          environment: QA
          postID: ${{ github.event.inputs.postID }}
          WORDPRESS_USERNAME: ${{ github.event.inputs.WORDPRESS_USERNAME }}
          WORDPRESS_PASSWORD: ${{ github.event.inputs.WORDPRESS_PASSWORD }}
  upload_to_s3:
    runs-on: ubuntu-latest
    needs: [clone_post]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Clone Post
        uses: upload_to_s3.yml
        with:
          environment: QA
          postID: ${{ github.event.inputs.postID }}
          WORDPRESS_USERNAME: ${{ github.event.inputs.WORDPRESS_USERNAME }}
          WORDPRESS_PASSWORD: ${{ github.event.inputs.WORDPRESS_PASSWORD }}

