name: Clone and Upload WordPress Post

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: string
        description: "The deployment environment (QA, SBOX, PROD)"
        default: "PROD"
      postID:
        required: true
        type: string
        description: "The ID of the post to clone"
        default: "27964"

jobs:
  clone_post:
    uses: ./.github/workflows/clone_post_job.yml
    with:
      environment: ${{ github.event.inputs.environment }}
      postID: ${{ github.event.inputs.postID }}

  upload_to_s3:
    needs: clone_post
    uses: ./.github/workflows/upload_to_s3_job.yml